# Generated by Django 5.2.7 on 2025-10-14 17:59

from django.db import migrations, models
from django.utils.text import slugify


def populate_team_slugs(apps, schema_editor):
    """Populate the 'slug' field for existing Team records by slugifying the 'name' field.

    Args:
        apps: Registry for historical models.
        schema_editor: The database schema editor.
    """

    Team = apps.get_model("users", "Team")
    for team in Team.objects.all():
        team.slug = slugify(team.name)
        team.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, null=True),
        ),
        migrations.RunPython(populate_team_slugs, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
