# Generated by Django 5.2.13 on 2026-05-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_team_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='team',
            name='users_team_slug_7df463_idx',
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['is_active'], name='users_team_is_acti_3dd195_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['slug', 'is_active'], name='users_team_slug_db3f7a_idx'),
        ),
    ]
