# Generated by Django 5.1.9 on 2025-05-13 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0015_alter_attachment_name'),
        ('research_products', '0004_remove_publication_date_publication_issue_and_more'),
        ('users', '0011_alter_membership_team_alter_membership_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['cluster'], name='allocations_cluster_9e2d25_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['request'], name='allocations_request_485eae_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['cluster', 'request'], name='allocations_cluster_4889c2_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationrequest',
            index=models.Index(fields=['team'], name='allocations_team_id_e6e033_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationrequest',
            index=models.Index(fields=['status'], name='allocations_status_45280d_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationrequest',
            index=models.Index(fields=['submitted'], name='allocations_submitt_28d764_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationrequest',
            index=models.Index(fields=['active'], name='allocations_active_54a53d_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationrequest',
            index=models.Index(fields=['expire'], name='allocations_expire_a0993f_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationrequest',
            index=models.Index(fields=['submitter'], name='allocations_submitt_248565_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationrequest',
            index=models.Index(fields=['team', 'status'], name='allocations_team_id_57a9fb_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationrequest',
            index=models.Index(fields=['submitter', 'status'], name='allocations_submitt_cfc50a_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationrequest',
            index=models.Index(fields=['team', 'submitter', 'status'], name='allocations_team_id_6bbc62_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationreview',
            index=models.Index(fields=['status'], name='allocations_status_965924_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationreview',
            index=models.Index(fields=['last_modified'], name='allocations_last_mo_15e9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationreview',
            index=models.Index(fields=['request'], name='allocations_request_daf984_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationreview',
            index=models.Index(fields=['reviewer'], name='allocations_reviewe_919641_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['uploaded'], name='allocations_uploade_ee2749_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['request'], name='allocations_request_b48705_idx'),
        ),
        migrations.AddIndex(
            model_name='cluster',
            index=models.Index(fields=['name'], name='allocations_name_9af528_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created'], name='allocations_created_05902d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['request'], name='allocations_request_22d7b3_idx'),
        ),
    ]
