# Generated by Django 5.2.3 on 2025-06-24 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0016_alter_cluster_name_and_more'),
        ('users', '0012_membership_users_membe_role_7a3cbb_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=128, null=True)),
                ('alloc_nodes', models.CharField(blank=True, max_length=128, null=True)),
                ('alloc_tres', models.TextField(blank=True, null=True)),
                ('derived_exit_code', models.IntegerField(blank=True, null=True)),
                ('elapsed', models.CharField(blank=True, max_length=32, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=128, null=True)),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('job_name', models.CharField(blank=True, max_length=512, null=True)),
                ('node_list', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('partition', models.CharField(blank=True, max_length=128, null=True)),
                ('qos', models.CharField(blank=True, max_length=128, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=64, null=True)),
                ('submit', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allocations.cluster')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.team')),
            ],
            options={
                'ordering': ['-submit'],
                'indexes': [models.Index(fields=['job_id'], name='allocations_job_id_c80640_idx'), models.Index(fields=['team', 'state'], name='allocations_team_id_768865_idx'), models.Index(fields=['state'], name='allocations_state_2e7a19_idx')],
            },
        ),
    ]
