# Generated by Django 5.2.4 on 2025-07-22 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0018_alter_jobstats_derivedexitcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='allocationreview',
            name='allocations_last_mo_15e9ea_idx',
        ),
        migrations.RenameField(
            model_name='allocationreview',
            old_name='last_modified',
            new_name='submitted',
        ),
        migrations.AlterField(
            model_name='allocationrequest',
            name='active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allocationrequest',
            name='expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allocationrequest',
            name='submitted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='allocationreview',
            index=models.Index(fields=['submitted'], name='allocations_submitt_2717e4_idx'),
        ),
    ]
