# Generated by Django 5.2.4 on 2025-07-30 17:31

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0018_alter_jobstats_derivedexitcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='allocationreview',
            name='allocations_last_mo_15e9ea_idx',
        ),
        migrations.RemoveField(
            model_name='allocationreview',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='allocationreview',
            name='submitted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='allocationrequest',
            name='submitted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddIndex(
            model_name='allocationreview',
            index=models.Index(fields=['submitted'], name='allocations_submitt_2717e4_idx'),
        ),
    ]
