# Generated by Django 5.2.8 on 2025-11-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0020_allocationrequest_allocations_team_id_f7dbff_idx'),
        ('users', '0014_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='access_mode',
            field=models.CharField(choices=[('WL', 'Whitelist'), ('BL', 'Blacklist'), ('OP', 'Open')], default='OP', max_length=2),
        ),
        migrations.AddField(
            model_name='cluster',
            name='access_teams',
            field=models.ManyToManyField(blank=True, null=True, to='users.team'),
        ),
    ]
