# Generated by Django 5.2.8 on 2025-11-17 17:19

import apps.allocations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0020_allocationrequest_allocations_team_id_f7dbff_idx'),
        ('users', '0014_team_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.CharField(max_length=64, unique=True)),
                ('jobname', models.CharField(blank=True, max_length=512, null=True)),
                ('account', models.CharField(blank=True, max_length=128, null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('submit', models.DateTimeField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=64, null=True)),
                ('exit_code', models.CharField(blank=True, max_length=10, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('qos', models.CharField(blank=True, max_length=128, null=True)),
                ('nodes', models.CharField(blank=True, max_length=128, null=True)),
                ('partition', models.CharField(blank=True, max_length=128, null=True)),
                ('sus', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allocations.cluster')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.team')),
            ],
            options={
                'ordering': ['-submit'],
            },
            bases=(apps.allocations.models.TeamModelInterface, models.Model),
        ),
        migrations.DeleteModel(
            name='JobStats',
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['jobid'], name='allocations_jobid_61b20f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['team', 'state'], name='allocations_team_id_30d221_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['state'], name='allocations_state_ef067d_idx'),
        ),
    ]
