# Generated by Django 5.2.8 on 2025-11-16 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0020_allocationrequest_allocations_team_id_f7dbff_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='access_mode',
            field=models.CharField(choices=[('WL', 'Whitelist'), ('BL', 'Blacklist'), ('OP', 'Open')], default='OP', max_length=2),
        ),
        migrations.AddField(
            model_name='cluster',
            name='access_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
