# Generated by Django 5.2.8 on 2025-11-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0021_cluster_access_mode_cluster_access_users'),
        ('users', '0014_team_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='access_users',
        ),
        migrations.AddField(
            model_name='cluster',
            name='access_teams',
            field=models.ManyToManyField(to='users.team'),
        ),
    ]
