# Generated by Django 5.2.8 on 2025-12-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0021_cluster_access_mode_cluster_access_teams'),
        ('users', '0014_team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='access_teams',
            field=models.ManyToManyField(blank=True, to='users.team'),
        ),
    ]
