# Generated by Django 5.2.13 on 2026-04-21 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0022_alter_cluster_access_teams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allocation',
            new_name='ResourceAllocation',
        ),
        migrations.RenameIndex(
            model_name='resourceallocation',
            new_name='allocations_request_fb4d70_idx',
            old_name='allocations_request_485eae_idx',
        ),
        migrations.RenameIndex(
            model_name='resourceallocation',
            new_name='allocations_cluster_b57f18_idx',
            old_name='allocations_cluster_4889c2_idx',
        ),
    ]
