# Generated by Django 5.2.13 on 2026-04-23 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0023_rename_allocation_resourceallocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceallocation',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_set', to='allocations.cluster'),
        ),
        migrations.AlterField(
            model_name='resourceallocation',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_set', to='allocations.allocationrequest'),
        ),
    ]
