# Generated by Django 5.2.14 on 2026-05-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0024_alter_resourceallocation_cluster_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobStats',
        ),
    ]
