# Generated by Django 5.2.14 on 2026-06-02 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0025_delete_jobstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationrequest',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_allocationrequest_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allocationreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourceallocation',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_set', to='allocations.cluster'),
        ),
    ]
