# Generated by Django 5.1.8 on 2025-05-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging', '0006_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='cid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
