# Generated by Django 5.1.9 on 2025-05-13 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging', '0006_auditlog_requestlog_cid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='applog',
            index=models.Index(fields=['name'], name='logging_app_name_9e6db9_idx'),
        ),
        migrations.AddIndex(
            model_name='applog',
            index=models.Index(fields=['level'], name='logging_app_level_d0cd2e_idx'),
        ),
        migrations.AddIndex(
            model_name='applog',
            index=models.Index(fields=['time'], name='logging_app_time_a67971_idx'),
        ),
        migrations.AddIndex(
            model_name='applog',
            index=models.Index(fields=['level', 'time'], name='logging_app_level_6b5b13_idx'),
        ),
        migrations.AddIndex(
            model_name='applog',
            index=models.Index(fields=['name', 'level', 'time'], name='logging_app_name_57a195_idx'),
        ),
        migrations.AddIndex(
            model_name='applog',
            index=models.Index(fields=['pathname', 'lineno'], name='logging_app_pathnam_35d89f_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['method'], name='logging_req_method_0ab60c_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['endpoint'], name='logging_req_endpoin_afc043_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['response_code'], name='logging_req_respons_b52108_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['remote_address'], name='logging_req_remote__bb910b_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['remote_address', 'response_code'], name='logging_req_remote__c6ce32_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['time'], name='logging_req_time_1746b4_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['cid'], name='logging_req_cid_01293a_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['user'], name='logging_req_user_id_7b77cb_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['user', 'time'], name='logging_req_user_id_5ebcf7_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['endpoint', 'method', 'time'], name='logging_req_endpoin_5a1cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['response_code', 'time'], name='logging_req_respons_9cf471_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['cid', 'time'], name='logging_req_cid_f39d18_idx'),
        ),
    ]
