# Generated by Django 5.2.14 on 2026-06-12 18:49

from django.db import migrations, models

# View combining all types of log records into a single query
# Unique IDs are created using the record IDs with a type prefix
_CREATE_VIEW = """
CREATE VIEW logging_feedentry AS
    SELECT
        'r' || id                    AS id,
        id                           AS record_id,
        timestamp                    AS timestamp,
        'request'                    AS record_type,
        endpoint                     AS summary,
        user_id                      AS user_id,
        cid                          AS cid,
        CAST(response_code AS TEXT)  AS status
    FROM logging_requestlog

    UNION ALL

    SELECT
        't' || id     AS id,
        id            AS record_id,
        date_created  AS timestamp,
        'task'        AS record_type,
        task_name     AS summary,
        NULL          AS user_id,
        NULL          AS cid,
        status        AS status
    FROM django_celery_results_taskresult

    UNION ALL

    SELECT
        'a' || id    AS id,
        id           AS record_id,
        timestamp    AS timestamp,
        'audit'      AS record_type,
        object_repr  AS summary,
        actor_id     AS user_id,
        cid          AS cid,
        'COMPLETED'  AS status
    FROM auditlog_logentry
"""

_DROP_VIEW = "DROP VIEW IF EXISTS logging_feedentry"


class Migration(migrations.Migration):

    dependencies = [
        ('logging', '0011_delete_applog'),
    ]

    operations = [
        migrations.RunSQL(sql=_CREATE_VIEW, reverse_sql=_DROP_VIEW),
        migrations.CreateModel(
            name='FeedEntry',
            fields=[
                ('id', models.CharField(max_length=20)),  # 19 characters for bigint +1 for record prefix
                ('record_id', models.BigIntegerField()),
                ('record_type', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField()),
                ('summary', models.TextField(null=True)),
                ('user_id', models.BigIntegerField(null=True)),
                ('cid', models.CharField(max_length=32, null=True)),
                ('status', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'logging_feedentry',
                'ordering': ['-timestamp'],
                'managed': False,
            },
        ),
    ]
