# Generated by Django 5.2.14 on 2026-06-11 15:55

from django.db import migrations, models



_CREATE_VIEW = """
CREATE VIEW logging_feedentry AS
    SELECT
        id,
        timestamp,
        'request'   AS source_type,
        endpoint    AS summary,
        user_id     AS actor_id
    FROM logging_requestlog

    UNION ALL

    SELECT
        id,
        date_created        AS timestamp,
        'task'              AS source_type,
        task_name           AS summary,
        NULL                AS actor_id
    FROM django_celery_results_taskresult

    UNION ALL

    SELECT
        id,
        timestamp,
        'audit'             AS source_type,
        object_repr         AS summary,
        actor_id
    FROM auditlog_logentry
"""

_DROP_VIEW = "DROP VIEW IF EXISTS logging_feedentry"

class Migration(migrations.Migration):

    dependencies = [
        ('logging', '0011_delete_applog'),
    ]

    operations = [
        migrations.RunSQL(sql=_CREATE_VIEW, reverse_sql=_DROP_VIEW),
        migrations.CreateModel(
            name='FeedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('request', 'Request'), ('task', 'Task'), ('audit', 'Audit')], max_length=16)),
                ('timestamp', models.DateTimeField()),
                ('summary', models.TextField(null=True)),
                ('actor_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'logging_feedentry',
                'ordering': ['-timestamp'],
                'managed': False,
            },
        ),
    ]
