"""Unit tests for the `AutoFilterBackend` class."""

from unittest.mock import Mock

from django.db import models
from django.test import TestCase
from django_filters import FilterSet, rest_framework as filters

from plugins.filters import AutoFilterBackend, AutoGeneratedFilterSet


class SampleModel(models.Model):
    """Sample database model for testing"""

    class Meta:
        app_label = 'test_AutoFilterBackend'

    bool_field = models.BooleanField()
    char_field = models.CharField(max_length=100)
    integer_field = models.IntegerField()
    date_field = models.DateField(auto_now_add=True)
    time_field = models.TimeField(auto_now_add=True)
    datetime_field = models.DateTimeField(auto_now_add=True)
    text_field = models.TextField()
    unknown_field = models.Field()


class FieldExpressionMapProperty(TestCase):
    """Test the `field_expression_map` property."""

    def test_returns_copy(self) -> None:
        """Verify the property returns a copy, not the internal reference."""

        backend = AutoFilterBackend()
        result = backend.field_expression_map
        self.assertIsNot(result, backend._field_expression_map)

    def test_copy_matches_original(self) -> None:
        """Verify the returned copy has the same contents as the internal map."""

        backend = AutoFilterBackend()
        result = backend.field_expression_map
        self.assertEqual(result, backend._field_expression_map)

    def test_mutating_copy_does_not_affect_original(self) -> None:
        """Verify changes to the returned copy do not propagate to the internal map."""

        backend = AutoFilterBackend()
        result = backend.field_expression_map
        result.clear()
        self.assertTrue(backend._field_expression_map, 'Mutating the copy cleared the internal map')


class BuildFilterAttrsMethod(TestCase):
    """Test filter attribute generation via the `_build_filter_attrs` method."""

    def setUp(self) -> None:
        self.backend = AutoFilterBackend()
        self.filter_attrs = self.backend._build_filter_attrs(SampleModel)

    def test_supported_field_generates_filters(self) -> None:
        """Verify a supported field type produces at least one filter entry."""

        matching_keys = [k for k in self.filter_attrs if k.startswith("integer_field")]
        self.assertTrue(matching_keys, 'No filters were generated for a supported field type')

    def test_unsupported_field_is_skipped(self) -> None:
        """Verify a field with an unmapped type produces no filter entries."""

        matching_keys = [k for k in self.filter_attrs if k.startswith("unknown_field")]
        self.assertFalse(matching_keys, 'Filters were generated for an unsupported field type')

    def test_all_values_are_filter_instances(self) -> None:
        """Verify every generated attribute is a `Filter` instance."""

        for param_name, filt in self.filter_attrs.items():
            self.assertIsInstance(filt, filters.Filter, f'{param_name} is not a Filter instance')

    def test_numeric_field_has_comparison_filters(self) -> None:
        """Verify numeric fields receive comparison operator filters."""

        for suffix in ("lt", "lte", "gt", "gte"):
            param = f"integer_field__{suffix}"
            self.assertIn(param, self.filter_attrs, f'Numeric field is missing {suffix} filter')

    def test_text_field_has_pattern_filters(self) -> None:
        """Verify text fields receive pattern matching filters."""

        for suffix in ("contains", "startswith", "endswith"):
            param = f"char_field__{suffix}"
            self.assertIn(param, self.filter_attrs, f'Text field is missing {suffix} filter')

    def test_date_field_has_component_filters(self) -> None:
        """Verify date fields receive date component extraction filters."""

        for suffix in ("year", "month", "day", "week", "week_day"):
            param = f"date_field__{suffix}"
            self.assertIn(param, self.filter_attrs, f'Date field is missing {suffix} filter')

    def test_time_field_has_component_filters(self) -> None:
        """Verify time fields receive time component extraction filters."""

        for suffix in ("hour", "minute", "second"):
            param = f"time_field__{suffix}"
            self.assertIn(param, self.filter_attrs, f'Time field is missing {suffix} filter')

    def test_datetime_field_has_date_and_time_filters(self) -> None:
        """Verify datetime fields receive both date and time component filters."""

        for suffix in ("year", "month", "day", "hour", "minute", "second"):
            param = f"datetime_field__{suffix}"
            self.assertIn(param, self.filter_attrs, f'DateTime field is missing {suffix} filter')

    def test_default_filters_applied_to_all_supported_fields(self) -> None:
        """Verify all supported fields receive the default filter set (exact, in, isnull)."""

        supported_fields = ("bool_field", "char_field", "integer_field", "date_field", "text_field")
        for field_name in supported_fields:
            self.assertIn(field_name, self.filter_attrs, f'{field_name} is missing exact filter')
            self.assertIn(f"{field_name}__in", self.filter_attrs, f'{field_name} is missing in filter')
            self.assertIn(f"{field_name}__isnull", self.filter_attrs, f'{field_name} is missing isnull filter')

    def test_negated_filters_are_generated(self) -> None:
        """Verify negated variants are generated for supported lookups."""

        self.assertIn("integer_field__not_in", self.filter_attrs, 'Missing not_in filter')
        self.assertIn("char_field__not_contains", self.filter_attrs, 'Missing not_contains filter')
        self.assertIn("bool_field__not_isnull", self.filter_attrs, 'Missing not_isnull filter')


class GetFiltersetClassMethod(TestCase):
    """Test the fetching of filterset classes via the `get_filterset_class` method."""

    def test_user_provided_filterset(self) -> None:
        """Verify existing filtersets are not overwritten."""

        mock_view = Mock()
        mock_view.filterset_class = Mock(spec=FilterSet)

        result = AutoFilterBackend().get_filterset_class(mock_view)
        self.assertEqual(result, mock_view.filterset_class, 'User defined filterset class was overwritten')

    def test_auto_generated_filterset_is_subclass(self) -> None:
        """Verify the generated filterset is a subclass of `AutoGeneratedFilterSet`."""

        mock_view = Mock()
        mock_view.filterset_class = None
        mock_view.filterset_fields = None

        mock_queryset = Mock()
        mock_queryset.model = SampleModel

        result = AutoFilterBackend().get_filterset_class(mock_view, mock_queryset)
        self.assertTrue(issubclass(result, AutoGeneratedFilterSet))

    def test_auto_generated_filterset_targets_correct_model(self) -> None:
        """Verify the generated filterset references the correct model."""

        mock_view = Mock()
        mock_view.filterset_class = None
        mock_view.filterset_fields = None

        mock_queryset = Mock()
        mock_queryset.model = SampleModel

        result = AutoFilterBackend().get_filterset_class(mock_view, mock_queryset)
        self.assertEqual(result.Meta.model, SampleModel, 'Generated filterset has incorrect model')

    def test_auto_generated_filterset_has_empty_fields(self) -> None:
        """Verify the generated filterset Meta uses an empty fields list."""

        mock_view = Mock()
        mock_view.filterset_class = None
        mock_view.filterset_fields = None

        mock_queryset = Mock()
        mock_queryset.model = SampleModel

        result = AutoFilterBackend().get_filterset_class(mock_view, mock_queryset)
        self.assertEqual(result.Meta.fields, [], 'Generated filterset Meta.fields is not empty')

    def test_auto_generated_filterset_contains_declared_filters(self) -> None:
        """Verify the generated filterset includes the expected filter declarations."""

        mock_view = Mock()
        mock_view.filterset_class = None
        mock_view.filterset_fields = None

        mock_queryset = Mock()
        mock_queryset.model = SampleModel

        result = AutoFilterBackend().get_filterset_class(mock_view, mock_queryset)
        declared = result.declared_filters

        self.assertIn("integer_field", declared, 'Missing exact filter on declared filters')
        self.assertIn("char_field__contains", declared, 'Missing text filter on declared filters')
        self.assertIn("date_field__year", declared, 'Missing date filter on declared filters')
