# Generated by Django 5.2.13 on 2026-04-15 18:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CR', 'Created'), ('SC', 'Succeeded'), ('FL', 'Failed')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_detail', models.TextField(blank=True, default='')),
            ],
        ),
    ]
