# Generated by Django 5.1.2 on 2024-10-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_preference_allocation_usage_thresholds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('GM', 'General Message'), ('RE', 'Upcoming Request Expiration'), ('RD', 'Request Has Expired')], max_length=2),
        ),
    ]
