# Generated by Django 5.2.9 on 2026-02-02 20:14

from django.db import migrations, models


def copy_message_to_html(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    Notification.objects.update(message_html=models.F('message_text'))


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notification_unique_user_type_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='message_text',
        ),
        migrations.AddField(
            model_name='notification',
            name='message_html',
            field=models.TextField(default=''),
        ),
        migrations.RunPython(copy_message_to_html, migrations.RunPython.noop),
    ]