# Generated by Django 5.2.9 on 2026-02-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notification_unique_user_type_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='message_html',
        ),
        migrations.AddField(
            model_name='notification',
            name='message_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
