"""Custom filter backends for the Django REST Framework.

Filter backends define how query parameters are handled in API requests.
This includes assigning parameters to endpoints, parsing values from incoming
requests, and applying parsed values in ORM queries.
"""

from dataclasses import dataclass

from django import views
from django.db import models
from django_filters import rest_framework as filters

__all__ = ['AutoFilterBackend', 'AutoGeneratedFilterSet', 'FilterDefinition']

# Sentinel value indicating that the query parameter suffix should
# default to the lookup expression name (e.g., "contains" -> __contains).
_DEFAULT_SUFFIX = object()


class AutoGeneratedFilterSet:
    """A factory generated filterset class

    This is an empty base class used to enable type checking/hinting
    on dynamically generated subclasses.
    """


@dataclass(frozen=True)
class FilterDefinition:
    """Definition of a single API query parameter and its ORM filtering behavior.

    Each instance describes how one query parameter should be named
    and how it translates into a django-filter `Filter` instance.
    For example, a config with `expr="contains"` on a field named
    `title` produces the query parameter `title__contains` and
    filters using the ORM `__contains` lookup.

    Setting the `suffix` value to `None` will generate a query parameter using
    the bare field name with no suffix.

    Attributes:
        expr: The ORM lookup expression used by `django-filter` (e.g., "exact", "contains", "in").
        negate: Whether to generate a negated (exclude) filter instead of a standard one.
        suffix: The suffix used in the query parameter name (e.g., "not_in").
    """

    expr: str
    negate: bool = False
    suffix: object = _DEFAULT_SUFFIX

    def param_name(self, field_name: str) -> str:
        """Build the query parameter name for a given field.

        Returns the field name with the suffix appended (e.g., "name__contains"),
        or just the field name if the suffix is `None` (e.g., "name").

        Args:
            field_name: The field name to attach a suffix to.

        Returns:
            The query parameter name string.
        """

        if self.suffix is None:
            return field_name

        elif self.suffix is _DEFAULT_SUFFIX:
            return f"{field_name}__{self.expr}"

        return f"{field_name}__{self.suffix}"

    def to_filter(self, field: models.Field) -> filters.Filter:
        """Create a `Filter` instance for a given model field.

        Uses django-filter's built-in field resolution to determine the
        appropriate filter class, then applies negation as needed.

        Args:
            field: The Django model field to create a filter for.

        Returns:
            A configured Filter instance.
        """

        # Resolve the correct filter class for the model field type and lookup expression
        # (e.g., CharField + "exact" resolves to CharFilter)
        filt = filters.FilterSet.filter_for_field(field, field.name, self.expr)
        filt.exclude = self.negate

        # List-based lookups like "in" need to accept comma-separated values (e.g., ?id__in=1,2,3).
        # Django-filter requires filter classes to inherit from `BaseInFilter` to enable this behavior.
        list_lookups = ("in",)
        if self.expr in list_lookups and filters.BaseInFilter not in type(filt).__mro__:
            wrapped_class = type(
                f"BaseIn{type(filt).__name__}",
                (filters.BaseInFilter, type(filt)),
                {},
            )

            filt = wrapped_class(
                field_name=filt.field_name,
                lookup_expr=filt.lookup_expr,
                exclude=filt.exclude,
            )

        return filt


class AutoFilterBackend(filters.DjangoFilterBackend):
    """Automatic query parameter generation for model-backed ViewSets.

     Given a ViewSet with no explicit `filterset_class` attribute, this
     backend inspects the underlying model and generates a full set of
     query parameters based on each field's type. Numeric fields receive
     comparison operators (lt, gte, ...), text fields receive pattern
     matching (contains, startswith, ...), and so on.

     When a ViewSet *does* define its own `filterset_class`, this
     backend defers to it entirely.
     """

    _default_filters = [
        FilterDefinition("exact", suffix=None),
        FilterDefinition("in"),
        FilterDefinition("in", negate=True, suffix="not_in"),
        FilterDefinition("isnull"),
        FilterDefinition("isnull", negate=True, suffix="not_isnull"),
    ]

    _numeric_filters = _default_filters + [
        FilterDefinition("lt"),
        FilterDefinition("lte"),
        FilterDefinition("gt"),
        FilterDefinition("gte"),
    ]

    _text_filters = _default_filters + [
        FilterDefinition("contains"),
        FilterDefinition("contains", negate=True, suffix="not_contains"),
        FilterDefinition("startswith"),
        FilterDefinition("endswith"),
    ]

    _date_filters = _numeric_filters + [
        FilterDefinition("year"),
        FilterDefinition("month"),
        FilterDefinition("day"),
        FilterDefinition("week"),
        FilterDefinition("week_day"),
    ]

    _time_filters = _numeric_filters + [
        FilterDefinition("hour"),
        FilterDefinition("minute"),
        FilterDefinition("second"),
    ]

    _date_time_filters = _numeric_filters + [
        FilterDefinition("year"),
        FilterDefinition("month"),
        FilterDefinition("day"),
        FilterDefinition("week"),
        FilterDefinition("week_day"),
        FilterDefinition("hour"),
        FilterDefinition("minute"),
        FilterDefinition("second"),
    ]

    # Maps database field types to the filter expressions supported by that field type.
    # This drives the dynamic `FilterSet` generation in `get_filterset_class`.
    _field_expression_map: dict[type[models.Field], list[FilterDefinition]] = {
        models.AutoField: _numeric_filters,
        models.BigAutoField: _numeric_filters,
        models.BigIntegerField: _numeric_filters,
        models.BooleanField: _default_filters,
        models.CharField: _text_filters,
        models.CommaSeparatedIntegerField: _default_filters,
        models.DateField: _date_filters,
        models.DateTimeField: _date_time_filters,
        models.DecimalField: _numeric_filters,
        models.DurationField: _default_filters,
        models.EmailField: _text_filters,
        models.FilePathField: _text_filters,
        models.FloatField: _numeric_filters,
        models.ForeignKey: _default_filters,
        models.GenericIPAddressField: _default_filters,
        models.IPAddressField: _default_filters,
        models.IntegerField: _numeric_filters,
        models.NullBooleanField: _default_filters,
        models.PositiveBigIntegerField: _numeric_filters,
        models.PositiveIntegerField: _numeric_filters,
        models.PositiveSmallIntegerField: _numeric_filters,
        models.SlugField: _text_filters,
        models.SmallAutoField: _numeric_filters,
        models.SmallIntegerField: _numeric_filters,
        models.TextField: _text_filters,
        models.TimeField: _time_filters,
        models.URLField: _text_filters,
        models.UUIDField: _default_filters,
    }

    @property
    def field_expression_map(self) -> dict[type[models.Field], list[FilterDefinition]]:
        """A mapping of database field types to their corresponding filter definitions."""

        return self._field_expression_map.copy()

    def _build_filter_attrs(self, model: type[models.Model]) -> dict[str, filters.Filter]:
        """Build a dictionary of filter instances for all fields on a model.

        Returns a mapping from url query parameters to filter instances
        suitable for use as class attributes on a `FilterSet`.

        Args:
            model: The Django model class to generate filters for.

        Returns:
            A dictionary mapping query parameter names to filter instances.
        """

        filter_attrs = {}
        for field in model._meta.get_fields():
            field_type = type(field)
            for expression in self._field_expression_map.get(field_type, []):
                filter_attrs[expression.param_name(field.name)] = expression.to_filter(field)

        return filter_attrs

    def get_filterset_class(self, view: views.View, queryset: models.Manager = None) -> type[filters.FilterSet]:
        """Get the `FilterSet` class for a given view.

        If the view defines a custom filterset class, that class is used.
        Otherwise, a `FilterSet` is dynamically generated with standard
        filters for every supported model field.

        Args:
            view: The view used to handle requests that will be filtered
            queryset: The queryset returning the data that will be filtered

        Returns:
            A `FilterSet` subclass.
        """

        # Default to the user defined filterset class
        # The super class method returns `None` if not defined
        if filterset_class := super().get_filterset_class(view, queryset=queryset):
            return filterset_class

        # Build all filter instances for the model
        filter_attrs = self._build_filter_attrs(queryset.model)

        # Create a `Meta` class with the model reference.
        filter_attrs['Meta'] = type('Meta', (), {'model': queryset.model, 'fields': []})

        # Dynamically construct a FilterSet subclass using the (class name, base classes, class attributes)
        return type('FactoryFilterSet', (self.filterset_base, AutoGeneratedFilterSet), filter_attrs)
