# Generated by Django 5.1.4 on 2025-02-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_products', '0003_remove_grant_group_remove_publication_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='date',
        ),
        migrations.AddField(
            model_name='publication',
            name='preparation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='submitted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
