# Generated by Django 5.2.6 on 2025-09-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_products', '0005_grant_research_pr_title_29205a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='preparation',
        ),
    ]
