# Generated by Django 5.2.14 on 2026-06-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_products', '0009_grant_description_alter_grant_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='pi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='grant_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
