name: Build

on:
  workflow_call:

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version
        id: version
        run: |
          release_tag=${{github.ref}}
          echo $release_tag
          exit 1
          echo "version=${release_tag#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Set package version
        run: poetry version ${{ steps.version.outputs.version }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: test-image:latest
          outputs: type=docker,dest=/tmp/test-image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-image
          path: /tmp/test-image.tar
