name: 🤖 Build

on:
  workflow_call:
    inputs:
      version:
        description: 'Set the version number of the compiled application.'
        default: '0.0.0'
        required: false
        type: string

jobs:
  build-docker:
    name: Docker
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Set package version
        run: poetry version "${{ inputs.version }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (${{ matrix.platform }})
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: keystone-api:latest
          outputs: type=docker,dest=keystone-api.tar
          platforms: ${{ matrix.platform }}

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: keystone-api-${{ matrix.platform }}
          path: keystone-api.tar

  build-python:
    name: Python Distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Set package version
        run: poetry version "${{ inputs.version }}"

      - name: Build Python distribution
        run: poetry build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: keystone-api-python
          path: dist