name: 🤖 Build

on:
  workflow_call:
    inputs:
      version:
        description: 'Set the version number of the compiled application.'
        default: '0.0.0'
        required: false
        type: string

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Set package version
        run: poetry version "${{ inputs.username }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: keystone-api:latest
          outputs: type=docker,dest=/tmp/keystone-api.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v3
        with:
          name: keystone-api
          path: /tmp/keystone-api.tar
