name: Build

on:
  workflow_call:

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: type=semver,pattern={{version}}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=/tmp/keystone-api.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v3
        with:
          name: keystone-api
          path: /tmp/keystone-api.tar
