name: Build

on:
  workflow_call:

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Get application version
        id: version
        run: echo "version=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')" >> $GITHUB_OUTPUT

      - name: Install Poetry
        if: startsWith(github.ref, 'refs/tags/v')
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Set package version
        if: startsWith(github.ref, 'refs/tags/v')
        run: poetry version ${{ steps.version.outputs.version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          labels: keystone-api-version=${{ steps.version.outputs.version }}
          tags: test-image:latest
          outputs: type=docker,dest=/tmp/test-image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-image
          path: /tmp/test-image.tar
