name: Publish Docker

on:
  workflow_call:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/keystone-api

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    name: Publish Image

    steps:

      - name: Fetch image artifact
        uses: actions/download-artifact@v3
        with:
          name: test-image
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/test-image.tar

      - name: Get application version
        id: version
        run: echo "version=$(docker inspect --format='{{index .Config.Labels "keystone-api-version"}}' test-image)" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }},${{ env.IMAGE_NAME }}:latest
