name: 🤖 Publish Package

on:
  workflow_call:
    inputs:
      version:
        description: 'Set the version number of the published application.'
        default: '0.0.0'
        required: false
        type: string

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    name: Docker Image

    environment:
      name: ghcr
      url: https://github.com/Better-HPC/keystone-api/pkgs/container/keystone-api

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Set package version
        run: poetry version "${{ inputs.version }}"

      - name: Fetch image artifact
        uses: actions/download-artifact@v5
        with:
          name: keystone-api-docker
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/keystone-api.tar

      - name: Define Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          images: ghcr.io/better-hpc/keystone-api
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title="Keystone API"
            org.opencontainers.image.description="API service for the Keystone HPC project."
            org.opencontainers.image.url="https://github.com/better-hpc/keystone-api"
            org.opencontainers.image.source="https://github.com/better-hpc/keystone-api"
            org.opencontainers.image.version="${{ inputs.version }}"
            org.opencontainers.image.authors="Better HPC LLC"
            org.opencontainers.image.revision="${{ github.sha }}"
            org.opencontainers.image.vendor="Better HPC LLC"
            org.opencontainers.image.ref.name="ghcr.io/better-hpc/keystone-api:${{ inputs.version }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image with multi-arch support
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          platforms: linux/amd64,linux/arm64
          outputs: type=docker,dest=/tmp/publish.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Publish image
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "docker"
          owner: "better-hpc"
          repo: "keystone-api"
          file: "/tmp/publish.tar"

  publish-python:
    name: Python Distribution
    runs-on: ubuntu-latest

    environment:
      name: cloudsmith
      url: https://app.cloudsmith.com/better-hpc/keystone-api

    steps:
      - name: Fetch build artifact
        uses: actions/download-artifact@v5
        with:
          name: keystone-api-python
          path: dist

      - name: Publish package
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "python"
          owner: "better-hpc"
          repo: "keystone-api"
          file: "dist/keystone_api-${{ inputs.version }}.tar.gz"

  trigger-docs:
    name: Trigger Docs
    runs-on: ubuntu-latest

    environment:
      name: docs
      url: https://github.com/Better-HPC/keystone-docs

    steps:
      - name: Update docs
        uses: better-hpc/keystone-docs/.github/actions/update-action/@main
        with:
          keystone-gitops-id: ${{ secrets.KEYSTONE_GITOPS_ID }}
          keystone-gitops-pk: ${{ secrets.KEYSTONE_GITOPS_PK }}
          repo-name: keystone-api
          tag: v${{ inputs.version }}
