name: Publish Docker

on:
  workflow_call:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/keystone-api

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    name: Publish Image

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Fetch image artifact
        uses: actions/download-artifact@v3
        with:
          name: keystone-api
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/keystone-api.tar

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
