name: 🤖 Publish Package

on:
  workflow_call:

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    name: Docker Image

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Fetch image artifact
        uses: actions/download-artifact@v4
        with:
          name: keystone-api-docker
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/keystone-api.tar

      - name: Define Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/keystone-api
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  publish-pypi:
    name: Python Distribution
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Fetch build artifact
        uses: actions/download-artifact@v4
        with:
          name: keystone-api-python
          path: dist

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          user: ${{ secrets.REPO_USER }}
          password: ${{ secrets.REPO_PASSWORD }}
