name: Pull Request

on:
  pull_request:

jobs:
  build:
    name: Build
    uses: ./.github/recipes/Build.yml

  test:
    name: Test
    needs: build
    uses: ./.github/recipes/Test.yml

  qa:
    name: QA
    needs: build
    uses: ./.github/recipes/QA.yml

  report-pr-status:
    name: Report PR Status
    runs-on: ubuntu-latest
    needs: [ test, qa ]
    if: always()

    steps:
      - name: Check PR status
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1