name: Test

on:
  workflow_call:

jobs:
  system-checks:
    name: System Checks
    runs-on: ubuntu-latest

    steps:
      - name: Fetch image artifact
        uses: actions/download-artifact@v3
        with:
          name: test-image
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/test-image.tar

      - name: Run project checks
        run: docker run test-image check

      - name: Run migration checks
        run: docker run test-image makemigrations --check

  app-tests:
    name: Application Tests
    runs-on: ubuntu-latest

    steps:
      - name: Fetch image artifact
        uses: actions/download-artifact@v3
        with:
          name: test-image
          path: /tmp

      - name: Run tests
        run: |
          docker load --input /tmp/test-image.tar
          docker run test-image test

  report-test-status:
    name: Report Test Status
    runs-on: ubuntu-latest
    needs: [ app-tests, system-checks ]
    if: always()

    steps:
      - name: Check test status
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
