name: Test

on:
  push:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: test-image:latest
          outputs: type=docker,dest=/tmp/myimage.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-image
          path: /tmp/myimage.tar

  app-tests:
    name: App Tests
    runs-on: ubuntu-latest
    needs: build-image

    steps:
      - name: Fetch image artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp

      - name: Launch container
        run: |
          docker load --input /tmp/myimage.tar
          docker run test-img test

  container-status:
    name: Container Status
    runs-on: ubuntu-latest
    needs: build-image

    steps:
      - name: Fetch image artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp

      - name: Launch container
        run: |
          docker load --input /tmp/myimage.tar
          docker run -d -p 8000:8000 test-img

      - name: Check API health
        run: |
          endpoint="http://localhost:8000/health"
          httpstatus=$(curl --silent --output /dev/null --write-out "%{http_code}" $endpoint)
          if [ "$httpstatus" -ne 200 ]; then
            curl $endpoint
            exit 1
          fi

  report-test-status:
    name: Report Test Status
    runs-on: ubuntu-latest
    needs: [ app-tests, container-status ]
    if: always()

    steps:
      - name: Check build status
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
