name: Test

on:
  push:

jobs:
  container-status:
    name: Container Status
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          tags: test-img:latest
          load: true

      - name: Launch container
        run: docker run -d -p 8000:8000 test-img

      - name: Check API health
        run: |
          status=$(curl --silent --output /dev/null --write-out "%{http_code}" http://localhost:8000/health)
          if [ "$status" == "200" ]; then
            echo "Container health check passed!"
          else
            echo "Container health check failed with status $status"
            exit 1
          fi
