name: Test

on:
  workflow_call:

jobs:
  api-status:
    name: API Status
    runs-on: ubuntu-latest

    steps:
      - name: Fetch image artifact
        uses: actions/download-artifact@v3
        with:
          name: test-image
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/test-image.tar

      - name: Check API health
        uses: addnab/docker-run-action@v3
        with:
          image: test-image
          run:  |
            endpoint="http://localhost:8000/health"
            httpstatus=$(curl --silent --output /dev/null --write-out "%{http_code}" $endpoint)
            
            # If the status is not 200, print the full status report from the endpoint
            if [ "$httpstatus" -ne 200 ]; then
              curl $endpoint
              exit 1
            fi

  function-tests:
    name: App Tests
    runs-on: ubuntu-latest

    steps:
      - name: Fetch image artifact
        uses: actions/download-artifact@v3
        with:
          name: test-image
          path: /tmp

      - name: Run tests
        run: |
          docker load --input /tmp/test-image.tar
          docker run test-image test

  report-test-status:
    name: Report Test Status
    runs-on: ubuntu-latest
    needs: [ api-status, function-tests ]
    if: always()

    steps:
      - name: Check test status
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
