name: Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          tags: crc-service-api:latest
          load: true
          push: false

      - name: Launch container
        run: docker run -d -p 8000:8000 crc-service-api

      - name: Check API health
        run: |
          status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health)
          if [ "$status" == "200" ]; then
            echo "Container health check passed!"
          else
            echo "Container health check failed with status $status"
            exit 1
          fi
