name: Test

on:
  workflow_call:

jobs:

  # System configuration tests including checks for obviously
  # incorrect settings and missing database migrations
  system-checks:
    name: System Checks
    runs-on: ubuntu-latest

    steps:
      - name: Fetch image artifact
        uses: actions/download-artifact@v3
        with:
          name: test-image
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/test-image.tar

      - name: Run project checks
        run: docker run test-image check

      - name: Run migration checks
        run: docker run test-image makemigrations --check

  # Integration test requiring all API health checks to pass
  # when launching the docker container with default settings.
  health-checks:
    name: API Health Checks
    runs-on: ubuntu-latest

    steps:
      - name: Fetch image artifact
        uses: actions/download-artifact@v3
        with:
          name: test-image
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/test-image.tar

      - name: Run API health checks
        run: |
          docker run --detach -p 8000:8000 test-image
          sleep 30  # Wait for API server to start
          
          http_status=$(wget -NS localhost:8000/health/ 2>&1 | grep "HTTP/" | awk '{print $2}')
          jq . index.html
          if [ "$http_status" -ne 200 ]; then
            exit 1
          fi

  # Run any/all application tests using the Django `test` utility
  app-tests:
    name: Application Tests
    runs-on: ubuntu-latest

    steps:
      - name: Fetch image artifact
        uses: actions/download-artifact@v3
        with:
          name: test-image
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/test-image.tar

      - name: Run tests
        run: docker run test-image test

  report-test-status:
    name: Report Test Status
    runs-on: ubuntu-latest
    needs: [ app-tests, system-checks, health-checks ]
    if: always()

    steps:
      - name: Check test status
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
